pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '16.x'   # or your desired Node.js version
    addToPath: true

- task: Npm@1
  inputs:
    command: 'install'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: Npm@1
  inputs:
    command: 'build'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: Npm@1
  inputs:
    command: 'test'
    workingDirectory: '$(Build.SourcesDirectory)'
